### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ubermajestix** [ebai101/splorganizer#1]
Hey there, 

I’m digging this repo, I’m using it to organize my Splice library onto an SD card. I have some modifications for windows and some ideas for enhancements but didn’t want to proceed without a license for the project. 

Can you add a license file? 

Thanks!

**Comment by ebai101** [comment]
Sure thing, just added a license. Feel free to fork the repo if you wish, I haven't worked on this in a while.

**Comment by ubermajestix** [comment]
Thanks!
